### ISSUE TITLE
YouTube and TMDB search links broken

### ISSUE THREAD

**Issue by eckomega** [kannibalox/IMDb-Scout#25]
Since the most recent update, the search links have not been working correctly. The movie name is not included in the search anymore. The results I receive are as follows.

**YouTube**
https://www.youtube.com/results?search_query=%22%22+1998+trailer

**TMDB**
https://www.themoviedb.org/search?query=

**Comment by kannibalox** [comment]
This should be fixed in https://github.com/kannibalox/IMDb-Scout/commit/2e513190eab68aeee6e2bf828308023420731650
