### ISSUE TITLE
Feature request - silent errors

### ISSUE THREAD

**Issue by photonman62** [kannibalox/IMDb-Scout#4]
Whenever trackers are having downtime, an intrusive dialog box pops up with the appropriate error message. If multiple trackers are down then there's multiple alerts per IMDB tab. With multiple IMDB tabs, this can get pretty annoying. I'd like to request a feature that could be enabled in the options, where instead of displaying an alert with the error, the tracker abbreviation would just show up differently. For example strikethrough+italics, or strikethrough+red, or something else like that.

That's all that would be needed for the feature, but an extra-smooth way of implementing this would be to display the error in a tooltip when the user mouses over the tracker abbreviation. 

As a "workaround" to stop the annoyance during longer downtimes (recently AHD for a few days, or TehC intermittently throughout the day) I just removed this section from the userscript:

```
		onerror: function(response) {
			alert('Call to ' + search_url + ' for ' + link_text + ' failed with status ' + response.statusText + '.\n' +
			'Please go to the URL in your browser and make sure it is valid.');
		},
```

**Comment by kannibalox** [comment]
I definitely see what you mean, I threw that in there mostly to catch sites with self-signed HTTPS certificates that would otherwise just not show up. I'll probably go with the strike-through+red, to be eye-catching but ignorable.

**Comment by photonman62** [comment]
Finally had an opportunity to test it - works great! _Much_ less annoying than before.
